### ISSUE TITLE
Drop shadow not rendered properly for some windows

### ISSUE THREAD

**Issue by heksesang** [decathorpe/elementary-nightly-rpms#12]
On Fedora 23, I see that some windows (for instance Firefox and Spotify) do not render the drop shadow correctly. It's not "fading" and rather just shows as a transparent black frame around the window.

It doesn't seem any of the built-in software has this issue (e.g. terminal, files, or switchboard), neither does IntelliJ.

Might test if Elementary has similar issues with the same apps during the weekend, just to see if it's a Fedora-specific issue.

**Comment by decathorpe** [comment]
This issue is known upstream, and already has a $50 bounty set on it.

As a side note, please check for issues upstream (launchpad) first before reporting them here - reporting the same (distro - independent) bugs in two places is inefficient.

https://bugs.launchpad.net/gala/+bug/1437173
