### ISSUE TITLE
You need me as another maintainer

### ISSUE THREAD

**Issue by rfkrocktk** [decathorpe/elementary-nightly-rpms#14]
If you need any other packaging work done, I'd be happy to help, I've been hoping for pantheon for quite some time now.

My email address [can be found on my GitHub page](https://github.com/rfkrocktk).

**Comment by decathorpe** [comment]
What work do you suggest you could do?

**Comment by rfkrocktk** [comment]
I can write specs, anything that you'd need. I have a vested interest in seeing elementary desktop on Fedora, and anything I could do to help would be awesome. How does your packaging system work? I created my own repository for media things [here](https://github.com/rfkrocktk/teekopolis-yum-repo).

**Comment by decathorpe** [comment]
Looks interesting. I use a program I wrote myself for regular builds, but if you can contribute .specs for unpackaged elementary software or improve existing spec files, that would be appreciated! The list of unpackaged software is in the README.md file :smile:

**Comment by rfkrocktk** [comment]
What's the typical process for working on this? Are you bzr cloning things locally? If you have a specific project for me to start on, I'd be happy to get there.

Do you know if we'll be able to run Wayland as the display manager?

**Comment by decathorpe** [comment]
Well, the initial packaging work involves more steps than I am willing to type into a comment box ... and just listing the steps is not really helpful, I think - do you want to continue this over IM or IRC or something?

**Comment by rfkrocktk** [comment]
If you create an IRC channel or something, I'm there. Otherwise, join the
hangops Slack group and pm me at "naftuli.kay" username:
https://signup.hangops.com/

**Comment by decathorpe** [comment]
Just did that. thanks!
