### ISSUE TITLE
File manager, Terminal and Scratch don't use Gala placement of buttons

### ISSUE THREAD

**Issue by heksesang** [decathorpe/elementary-nightly-rpms#15]
These apps (and maybe all Pantheon specific apps) have their X placed in the top-right corner and they have no maximize button, unlike all other apps that seem to follow my Gala configuration.

This is on Fedora 23.

**Comment by decathorpe** [comment]
GTK apps with HeaderBars use a different setting for their button placement than the gala settings.
And, as those settings are global for all desktop environments, I won't change their default values.

You can, however, change the button layout using gnome-tweak-tool, as always (or by using specific xsettings overrides set in gsettings).
