### ISSUE TITLE
[F24] switchboard-plug-mouse-touchpad crashes (core-dumped) 

### ISSUE THREAD

**Issue by alunux** [decathorpe/elementary-nightly-rpms#16]
In System Settings -> Mouse & Touchpad, if you click it, Switchboard will be crashed. Output from terminal:
```
[ERROR 09:45:21.346661] [GLib-GIO] Settings schema 'org.gnome.desktop.peripherals.touchpad' does not contain a key named 'scroll-method'
Trace/breakpoint trap (core dumped)
```

**Comment by decathorpe** [comment]
Patch is integrated with the automatic nightly builds now, and also with the stable package builds. Thanks for your help!

**Comment by decathorpe** [comment]
@alunux The patch doesn't apply to the latest bzr snapshot anymore, so I'll have to remove the mouse-touchpad plug from the nightly builds for now, as it seems

**Comment by alunux** [comment]
@decathorpe It's ok. I will review it later :)
