### ISSUE TITLE
[feature-request] packaging current elementary icon theme

### ISSUE THREAD

**Issue by daniel-wtd** [decathorpe/elementary-nightly-rpms#20]
Hey,
is it possible to pack the current icon theme from elementary in your repo?

Small addition:
This also can help, to have some missing icons, like wingpanel-indicator-notification icon.

**Comment by decathorpe** [comment]
I added packages for elementary-icon-theme to the stable and nightly copr.

**Comment by daniel-wtd** [comment]
Cool, thanks. I'll have a look at it.
