### ISSUE TITLE
[RFE] Package pantheon-greeter 

### ISSUE THREAD

**Issue by Conan-Kudo** [decathorpe/elementary-nightly-rpms#22]
Would you please package [pantheon-greeter](https://launchpad.net/pantheon-greeter) for LightDM?

**Comment by decathorpe** [comment]
Hm ... What would be the benefit of having pantheon-greeter over using the default (gdm)?

**Comment by Conan-Kudo** [comment]
It's much lighter and looks nice in combination with Pantheon. In Fedora, the only variant that uses GDM is the Workstation Edition. Even the Cinnamon spin uses LightDM, though with the default greeter.

**Comment by decathorpe** [comment]
I'll look into it.

**Comment by decathorpe** [comment]
Stable and nightly repositories now include preliminary pantheon-greeter builds, I'm not sure they are usable yet.
