### ISSUE TITLE
[RFE] Package pantheon-agent-polkit

### ISSUE THREAD

**Issue by Conan-Kudo** [decathorpe/elementary-nightly-rpms#23]
Would you please package [pantheon-agent-polkit](https://launchpad.net/pantheon-agent-polkit)? Applications that have polkit integration (AppCenter, systemctl, virt-manager, etc.) need it to function properly within the desktop environment.

**Comment by decathorpe** [comment]
There is a pantheon-agent-polkit package in the stable repo now, I'll add snapshot builds to the nightly repo at a later time.

**Comment by decathorpe** [comment]
`pantheon-agent-polkit` nightly builds are now in this repo, too.
