### ISSUE TITLE
[RFE] Package switchboard gnome-control-center panel integration plugs

### ISSUE THREAD

**Issue by Conan-Kudo** [decathorpe/elementary-nightly-rpms#26]
The remaining big pieces of missing functionality in switchboard requires [switchboard-gnome-control-center-override](https://code.launchpad.net/~elementary-os/elementaryos/switchboard-gnome-control-center-override) and [switchboard gnome-control-center plugs](https://code.launchpad.net/~elementary-apps/pantheon-plugs/dynamic-gcc-plug-loki).

Please package them.

**Comment by decathorpe** [comment]
This code now only works with unity-control-center, which I won't package for fedora.
