### ISSUE TITLE
switchboard (file sharing) causes crash of switchboard

### ISSUE THREAD

**Issue by daniel-wtd** [decathorpe/elementary-nightly-rpms#27]
Hey,
unfortunately some switcboard plus/functions are causing the switchboard to crash:

File-Sharing
ERROR: 

```
[GLib-GIO] Settings schema 'org.gnome.desktop.file-sharing' does not contain a key named 'bluetooth-obexpush-enabled'
```

Regards! :)

**Comment by decathorpe** [comment]
It seems that gnome 3.20 and 3.22 don't have that gsettings key anymore, as it is not present on my system. Can you confirm that (using dconf-editor or CLI)?

**Comment by daniel-wtd** [comment]
in my dconf-editor this is present. 
Accoring to github (https://github.com/GNOME/gnome-user-share/blob/master/data/org.gnome.desktop.file-sharing.gschema.xml.in.in) it is part of gnome-user-share, which is installed for me.

**Comment by decathorpe** [comment]
That's strange, I also have gnome-user-share installed and that gsettings key isn't present on my system (fedora 25).

Is it possible that this has been a setting in gnome-user-share 3.16 or 3.18 and has been removed with a recent version? (And elementary depending on the "old" version of gnome in the ubuntu repositories?)

**Comment by daniel-wtd** [comment]
That can be indeed a problem. If your'e on F25a, you will have gtk 3.22 which has a ton of changes to 3.18/3.20 :/

Will have a look at F25a and this problem.

**Comment by decathorpe** [comment]
This bug is now tracked upstream at https://github.com/elementary/switchboard-plug-sharing/issues/10.
