### ISSUE TITLE
[Feature-Request] Please package elementary-tweaks

### ISSUE THREAD

**Issue by daniel-wtd** [decathorpe/elementary-nightly-rpms#28]
It's basically an "elementary part" ;-) to switch themes without some dconf-commands or using gnome-tweak-tool.

**Comment by decathorpe** [comment]
Quote from the project's home page on launchpad:

> This project is exclusively for elementary OS 0.3 Freya
> (...)
> AS OF FEBUARY 2015, THIS PROJECT IS NO LONGER MAINTAINED.

I don't think it will even work with the packages from 0.4 (loki)

**Comment by daniel-wtd** [comment]
It does work with 0.4 :)

**Comment by decathorpe** [comment]
Yeah ... I am not really inclined to package software that has been abandoned for one and a half years.

Can you get by with using gnome-tweak-tool / dconf or doesn't it do all you want?

**Comment by daniel-wtd** [comment]
I can totally understand this.
For most stuff gnome-tweak-tool works fine. :) It just has a ton of stuff, which isn't used in elementary.

But changing themes is the same.

Other stuff can be done with cli or dconf.

**Comment by decathorpe** [comment]
Good. Then I'll close this issue for now.
