### ISSUE TITLE
switchboard (light-locker) causes crash of switchboard

### ISSUE THREAD

**Issue by daniel-wtd** [decathorpe/elementary-nightly-rpms#29]
Unfortunately the "Privacy and Security" Section is causing a crash.

ERROR:

```
[GLib-GIO] Settings schema 'apps.light-locker' is not installed
```

**Comment by decathorpe** [comment]
I am aware of that crash. But, as I currently can't get the missing pantheon-greeter to compile from source, there's nothing I can do about it (for now).

As soon as pantheon-greeter is packaged, I will revisit this issue.

**Comment by daniel-wtd** [comment]
Ah, I see :) So I'll be patient and wait for it.

**Comment by decathorpe** [comment]
This crash *should* be fixed now ...

**Comment by daniel-wtd** [comment]
Awesome =) Will try it out
