### ISSUE TITLE
switchboard not unlockable (user-accounts, locale) 

### ISSUE THREAD

**Issue by daniel-wtd** [decathorpe/elementary-nightly-rpms#30]
Hey, I'm unable to use the "unlock" Button. It's causing a waring:

WARNING:
```
[Gtk] Error acquiring permission: Failed to acquire permission for action-id org.pantheon.switchboard.user-accounts.administration
```

Same can be seen in org.pantheon.switchboard.locale.administration

**Comment by decathorpe** [comment]
Did you install the new pantheon-agent-polkit package?
(It's only in elementary-stable right now)

**Comment by daniel-wtd** [comment]
Have updated, installed the mentioned package and rebooted. Unfortunately it does not work.

Error is the same.

**Comment by decathorpe** [comment]
I just figured out an error in the pantheon-agent-polkit package: The corresponding autostart file is not included in the sources and not installed by default, but is part of the upstream debian packaging. I adapted and included that file for a rebuild of the package - the new build is on copr right now.

Can you update to version 0.1-2, reboot, and test if it works now?

In doubt, check if a "/usr/libexec/pantheon-1-polkit/pantheon-agent-polkit" or "pantheon-agent-polkit" process is now running in the pantheon session.

**Comment by daniel-wtd** [comment]
Hey,
thanks a lot. The password dialog works now! :)

btw: Awesome reaction time and thanks for the effort you are putting in here.

**Comment by decathorpe** [comment]
Great! :)

And thanks for the kind words, packaging elementary stuff is shaping up to be kind of a lot of work :smile:
