### ISSUE TITLE
fedora 25 - on wayland - freeze and restart

### ISSUE THREAD

**Issue by metal3d** [decathorpe/elementary-nightly-rpms#36]
Hi,

First: nice to see that someone tries to make Pantheon usable on Fedora :)

I'm on Fedora 25, the "X11" session is (near to be) ok but Wayland session breaks. Mouse cursor freeze and after 10-15s the session stops - then it returns to the login screen.

I don't find any logs (or maybe I don't look at the right place)

**Comment by decathorpe** [comment]
That is to be expected - the Pantheon session doesn't officially support running on wayland yet.

I will mention this somewhere as a "Known Bug" or something (and move the wayland session files to a subpackage that isn't installed by default).

**Comment by decathorpe** [comment]
I moved the wayland session into an "experimental" subpackage as of https://github.com/decathorpe/elementary-nightly-rpms/commit/b062c7148a88d31967cce9c9cdf1d6ec4858d019.
