### ISSUE TITLE
Pantheon shortcuts and/or menus ?

### ISSUE THREAD

**Issue by metal3d** [decathorpe/elementary-nightly-rpms#37]
Hi, 

I'm on the X11 session on Fedora 25 and Pantheon seems to works. But I cannot stop session, there is no menu (right click menu on desktop), no "end session" in Activity menu,  no "exec" shortcut (as ALT+F2 or Mod+F2)...

Some shortcuts works, as Mod+D for example.

I installed pantheon-session and pantheon-desktop (+ pantheon-files)

PS: I'm using an azerty keyboard (french)

**Comment by decathorpe** [comment]
You can always use the session menu at the top right corner of the screen (rightmost wingpanel indicator) to terminate the session.

I am aware that not all keyboard shortcuts work, but I am unwilling to override settings that also change the behaviour of GNOME.

**Comment by metal3d** [comment]
I'm sorry but I don't see that button

![image](https://cloud.githubusercontent.com/assets/100080/20854947/87baf18c-b8f8-11e6-9cfa-b9f243706912.png)

Maybe something is wrong with "theme"... But I don't have any control to Pantheon settings.

BTW: great work to attempt to make Pantheon working on Fedora

**Comment by metal3d** [comment]
Changed theme gtk theme to "pantheon", still no button. I really think there is something wrong for some configuration like mine.

**Comment by metal3d** [comment]
Ok found... I had to install wingpanel-indicator-session

Now... I only have to fix my mouse problems. Sorry for that bad issue.

**Comment by decathorpe** [comment]
No Problem.
Usually all indicators should be pulled in too when you install the session (or wingpanel, because they "Supplement" wingpanel), obviously that didn't happen here ...

**Comment by metal3d** [comment]
Actually I just understand that I installed the nightly build and not stable build (from your copr repo) - So I removed entire packages, disabled nightly and activate stable. It's ok.

I only have two problems I will create issue, and you can remove them if they are not relevants.
