### ISSUE TITLE
Wingpanel not working

### ISSUE THREAD

**Issue by gabboman** [decathorpe/elementary-nightly-rpms#4]
When I start pantheon wingpanel doesn't start. If i maximize google chrome, it leaves a space in the top bar. I can't start any app that is not in the dock.

I don't know whre to search logs, and I can't start any terminal. What could I do?

I'm using fedora 23

Thanks for your help

**Comment by decathorpe** [comment]
Did you install slingshot-launcher and some wingpanel indicators? If not -- wingpanel is empty and transparent by default - which could be what you are seeing.

**Comment by gabboman** [comment]
all those packages are installed, it doesn't work. It says that all the
indicators are installed and the slinghsot launcher too. But the problem
persits :(

2016-05-14 23:16 GMT+02:00 Fabio Valentini <notifications@github.com>:

**Comment by decathorpe** [comment]
Which theme are you using? That might also cause issues.
for me it works with the adwaita and Paper GTK themes

**Comment by gabboman** [comment]
I'm using adwaita, so it's not a theme problem. Maybe in the config file
there isn't any launcher or any indicator?

Where can I search for my config files? Thank you

2016-05-15 0:38 GMT+02:00 Fabio Valentini <notifications@github.com>:

**Comment by decathorpe** [comment]
That shouldn't be an issue - for example, I just installed the packages on my system and it works ... so I really can't tell what's going wrong here.

If you want to look at the logs for your user session, you can use ```journalctl --user -xb``` to view the full log since the last reboot or  ```journalctl --user -xb | grep wingpanel``` only for messages by wingpanel.

**Comment by gabboman** [comment]
Hi, i append my logs to the mail, I dont know what will git do with this.

Log is just the log with the word wingpanel, and logFull is my full system
log.

Thanks for your help

2016-05-15 18:45 GMT+02:00 Fabio Valentini <notifications@github.com>:

**Comment by decathorpe** [comment]
I just looked at both log files, and there is no indication whatsoever why wingpanel is crashing on your system. This is starting to look very weird.

**Comment by gabboman** [comment]
Well, I launched it with the debug option and piped the output to that file. 
[wingpanel.txt](https://github.com/decathorpe/elementary-nightly-rpms/files/276282/wingpanel.txt)

I hope this can help in some way, thank you for your help

**Comment by decathorpe** [comment]
Do you have the "zeitgeist" package installed? It is the only difference I can spot between logs on your system and mine.

If that's causing the crashes, I'll add zeitgeist as an explicit dependency with the next update.

**Comment by gabboman** [comment]
Now I installed it and kinda feel stupid. Still invisible, but after killall wingpanel & wingpanel -d I see a battery indicator. I add the logs, but this is still invisible :/

Thanks for your help

[wingpanelwithpacket.txt](https://github.com/decathorpe/elementary-nightly-rpms/files/276363/wingpanelwithpacket.txt)

**Comment by decathorpe** [comment]
Well, the panel itself is always transparent and only some indicators are showing - so if you are using an icon theme which does not support those icons it might show up as "empty"

**Comment by decathorpe** [comment]
Did any of the wingpanel updates that happened in the meantime resolve your issue?

**Comment by daniel-wtd** [comment]
Hey,

I had the very same problem. After installing fedy and installing paper-theme from there, everything is working fine. It looks not so neat like in the elementaryOS, but works for now =)

Ah, and I had to reboot (not only to relogin).

**Comment by decathorpe** [comment]
Which theme were you using? With the default (Adwaita), it works here - the text might just be too dark / the panel too opaque in front of dark desktop wallpapers to see properly?

**Comment by daniel-wtd** [comment]
Hey,
after a fresh installation I am not able to start wingpanel.

You can see some logs from manually starting wingpanel in this pastebin.
http://pastebin.com/RPnG0V62

This happens, no matter which theme I'm chosing or icon-theme is enabled.
You can see the wingpanel flickering a bit and then it crashes.

**Comment by decathorpe** [comment]
This seems strange, I can start wingpanel here even without elementary-dpms-helper installed, but it seems to crash on your system because it is missing.
Can you try launching wingpanel again, after installing elementary-dpms-helper?

**Comment by daniel-wtd** [comment]
Hey,
thanks for the very fast answer and help. :+1: 

After installing "elementary-dpms-helper" wingpanel starts.

It has some weird transparent border on top or looks a little faded, but this seems to be theming thing. This border is only visible in "transparent mode"

The following errors are still  visible, when starting wingpanel manually:
-> most likely theming related
```
[WARNING 10:57:27.754752] [Gtk] (gtkicontheme.c:5481):gtk_icon_theme_lookup_by_gicon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[WARNING 10:57:27.754771] [Gtk] (gtkicontheme.c:2226):gtk_icon_theme_choose_icon_for_scale: runtime check failed: ((flags & GTK_ICON_LOOKUP_GENERIC_FALLBACK) == 0)
[FATAL 10:57:27.764941] wingpanel_widgets_overlay_icon_set_main_icon_name: assertion 'self != NULL' failed
[FATAL 10:57:27.765265] wingpanel_widgets_overlay_icon_set_main_icon_name: assertion 'self != NULL' failed
WARNING 10:57:27.809138] [Gtk] Theme parsing error: gtk-widgets.css:26:27: The style property GtkWidget:link-color is deprecated and shouldn't be used anymore. It will be removed in a future version
[WARNING 10:57:27.809341] [Gtk] Theme parsing error: gtk-widgets.css:60:13: The :insensitive pseudo-class is deprecated. Use :disabled instead.
[WARNING 10:57:27.809380] [Gtk] Theme parsing error: gtk-widgets.css:62:21: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'
[WARNING 10:57:27.809410] [Gtk] Theme parsing error: gtk-widgets.css:66:21: The '-gtk-image-effect' property has been renamed to '-gtk-icon-effect'
```

Other errors:
```
[FATAL 10:57:27.831147] [GLib-GIO] g_file_get_child: assertion 'G_IS_FILE (file)' failed
[FATAL 10:57:27.831181] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 10:57:27.831196] [GLib-GIO] g_file_get_child: assertion 'G_IS_FILE (file)' failed
[FATAL 10:57:27.831210] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 10:57:27.831225] gee_abstract_collection_get_size: assertion 'self != NULL' failed
[WARNING 10:57:27.831240] Theme.vala:508: Currently selected gtk+ theme 'egtk' does not provide a dock theme, fallback to the built-in defaults!
[FATAL 10:57:28.008535] [GLib] g_hash_table_get_keys: assertion 'hash_table != NULL' failed

** (process:5903): CRITICAL **: string_contains: assertion 'self != NULL' failed

** (process:5903): CRITICAL **: string_contains: assertion 'self != NULL' failed
[08:57:28.453082 Critical] PlugsManager.vala:58: get_plug () not found in /usr/lib64/switchboard/hardware/pantheon-power/systemd
[08:57:28.567479 Critical] PlugsManager.vala:58: get_plug () not found in /usr/lib64/switchboard/system/pantheon-useraccounts/guest-session-toggle
```

**Comment by decathorpe** [comment]
Well, I can do nothing about the remaining errors .. and as you said, the optical problems are issues with the theme (or wingpanel looking _only_ right with the official elementary theme and *exclusively* with GTK+ 3.18).

The sad thing is: the elementary devs don't want to / cannot support the newer GTK versions (everything newer than 3.18) found in fedora 24+.
