### ISSUE TITLE
gsignond projects need packaging for Fedora

### ISSUE THREAD

**Issue by codygarver** [decathorpe/elementary-nightly-rpms#40]
Upstream gsignond projects that need packaging are:
* [gsignond](https://gitlab.com/accounts-sso/gsignond)
* [libgsignon-glib](https://gitlab.com/accounts-sso/libgsignon-glib)
* Not sure if you need anything else from [here](https://gitlab.com/groups/accounts-sso).

elementary gsignond projects:
* [gsignond-extension-pantheon](https://launchpad.net/gsignond-extension-pantheon)
* [gsignond-plugin-mail](https://launchpad.net/gsignond-plugin-mail)
* [gsignond-plugin-lastfm](https://launchpad.net/gsignond-plugin-lastfm)

**Comment by decathorpe** [comment]
I guess I'll have to use recent git snapshots of those (for now), since the last stable release of, for example, `gsignond`, is more than 2 years old?

**Comment by decathorpe** [comment]
Just for the record, it seems @tintou is already working on this upstream:
https://gitlab.com/accounts-sso/gsignond/tree/tintou/wip/fedora

**Comment by decathorpe** [comment]
The following packages are now available in fedora repositories:

- gsignond
- libgsignon-glib

I will work on getting the additional extensions ready soon.
