### ISSUE TITLE
[F26] Pantheon Session does not launch

### ISSUE THREAD

**Issue by aft3rlife** [decathorpe/elementary-nightly-rpms#41]
I'm not sure if this issue is related to `the pantheon wayland session doesn't work yet` or not but it seems like something is causing the pantheon session to crash when selecting it from gdm.

Let me know if I can help with any logs/stack traces as I'm not sure where those would be.

**Comment by decathorpe** [comment]
I am aware of this issue, but I have not yet been able to pinpoint the cause myself. If there's any news, I'll update this issue.

**Comment by decathorpe** [comment]
Upon investigation, the session fails to launch because gnome-settings-daemon is not found. This GNOME  autostart component was renamed / split into ~15 separate binaries. I will have to adapt pantheon-session-settings to adapt to those changes.

**Comment by decathorpe** [comment]
I think I have fixed the issue.

If you're using the stable package versions, fedora 26 should get an [update](https://bodhi.fedoraproject.org/updates/FEDORA-2017-2c888eca3f) tomorrow-ish, and if you're using the nightly snapshots, an updated build of `pantheon-session-settings` should be available in an hour.

**Comment by aft3rlife** [comment]
I'm using the nightly snapshots. Looks like it's working fine now!
