### ISSUE TITLE
pantheon-greeter points to nonexistent wallpaper

### ISSUE THREAD

**Issue by nekohayo** [decathorpe/elementary-nightly-rpms#43]
/etc/lightdm/pantheon-greeter.conf  contains this by default:

```
#activate-numlock=true
#default-wallpaper=/usr/share/backgrounds/elementaryos-default
#high-contrast=false
#onscreen-keyboard=false
#screensaver-timeout=60
```

...which seems to indicate that it looks for /usr/share/backgrounds/elementaryos-default, which does not exist on the Fedora packages. Instead, it might as well point to /usr/share/backgrounds/default.png (which is the Fedora wallpaper) or something in /usr/share/backgrounds/elementary (but that makes it dependent on the elementary-wallpapers* packages...)

**Comment by decathorpe** [comment]
Do you have the pantheon-greeter package from fedora, or from the elementary-nightly COPR repository? Dropping the output from `rpmquery pantheon-greeter` here is enough.

All those settings are commented out in the .conf file, so they have no effect. However, I'll update them to point to an existing file.

**Comment by decathorpe** [comment]
Turns out, I already had a fix for this for the nightly packages. With the next round of fedora updates, this should now be fixed with stable packages as well.

Please re-open this issue if it doesn't work.
