### ISSUE TITLE
Add shortcut for multitasking view

### ISSUE THREAD

**Issue by jangernert** [decathorpe/elementary-nightly-rpms#5]
Apparently there is no keyboard-shortcut setting for the multitasking view like for all the other things gala can to. To initiate the multitasking view you need to execute:

```dbus-send --session --dest=org.pantheon.gala --print-reply /org/pantheon/gala org.pantheon.gala.PerformAction int32:1```

So there should be a system-wide shortcut by default that executes this command. I think it was super+s in elementary OS?

**Comment by decathorpe** [comment]
The gala package installs a launcher shortcut for this action that you can add to plank.

And: I'm not willing to package setting overrides with elementary packages that will mess with people's primary desktop (GNOME) settings, if that's what you're asking ... I'm sure you understand that would create more problems than it would solve.

I'll package the switchboard plug that allows setting keyboard shortcuts soon, then everybody can set shortcuts as needed / desired.

**Comment by jangernert** [comment]
Sounds fair enough
