### ISSUE TITLE
slinghsot launcher

### ISSUE THREAD

**Issue by harethzoubi** [decathorpe/elementary-nightly-rpms#6]
hello

im using fedora 23 and install this slinghsot launcher but not working i dont found it on app how i can start it ?

**Comment by decathorpe** [comment]
Did you start a Pantheon session from your login screen? That should launch wingpanel and the slingshot launcher (leftmost button on wingpanel).

**Comment by harethzoubi** [comment]
no i didnt install pantheon session .. itry to start it on gnome .. now i understand .. i must install pantheon ?

**Comment by decathorpe** [comment]
Yes. Slingshot is essentially an indicator for wingpanel now, and you can (sensibly) only use that within a pantheon desktop session.

Running slingshot on its own doesn't work.
