### ISSUE TITLE
Super + Space doesn't open the Applications menu

### ISSUE THREAD

**Issue by heksesang** [decathorpe/elementary-nightly-rpms#7]
The Super + Space key combo from Elementary doesn't work, so I have no shortcut to open the Applications menu.

This is on Fedora 23.

**Comment by decathorpe** [comment]
I know the "default keybindings" from elementary OS don't work, but I have no intention of overriding GNOME keybindings with my packages (and possibly breaking most peoples main desktop).

I am aware this is an annoyance, but I am unwilling to ship settings overrides that would affect other desktop environments.

You should be able to set Super + Space to open slingshot manually, though.

**Comment by heksesang** [comment]
Any hint on how to actually do that? I have no idea how to invoke the command to open the slingshot window. :)

**Comment by decathorpe** [comment]
you can do:
```
gsettings set org.pantheon.desktop.gala.behavior overlay-action "'wingpanel --toggle-indicator=app-launcher'"
```
to use the "super" key alone - this also doesn't interfere with gnome

**Comment by heksesang** [comment]
Doesn't do anything on my system. The system doesn't seem to execute whatever is in the gala behaviour properties. Also, running 'wingpanel --toggle-indicator=app-launcher' in terminal just gives an error that --toggle-indicator isn't an option, it's not possible to invoke the command through the terminal to test that the command itself works?

**Comment by decathorpe** [comment]
I didn't test this myself, because I got it from the elementary developers directly.
