### ISSUE TITLE
Top panel rendering issues

### ISSUE THREAD

**Issue by heksesang** [decathorpe/elementary-nightly-rpms#8]
In the top panel, if you focus it by opening anything from it, the text and symbols except the notifications symbol goes much darker. The focus is also kept on the top panel if there are no windows open yet, keeping the darker colour of the text and symbols.

Also, the transparent gray background of the top panel is missing.

This is on Fedora 23.

**Comment by decathorpe** [comment]
This is a known issue with the default GTK theme, adwaita. Using the egtk theme (official elementary theme), this problem does not occur and the panel rendering looks like on elementary OS.

I reached out to upstream about this issue, but they are unwilling / unable to support other themes than their own (or shipping a custom CSS file for wingpanel on adwaita).
