### ISSUE TITLE
Selecting a wallpaper hides the ones following that one

### ISSUE THREAD

**Issue by heksesang** [decathorpe/elementary-nightly-rpms#9]
In System Settings -> Desktop -> Wallpaper, if you click a wallpaper, any wallpapers after it in the list are hidden until you deselect that wallpaper by clicking it again.

This is on Fedora 23.

**Comment by decathorpe** [comment]
I can confirm this also happens on fedora 24. I am looking into whether it also happens on elementary OS 0.4 beta.

**Comment by decathorpe** [comment]
It seems this issue is fedora-specific, I'll try to get someone from elementary to look into it.

**Comment by decathorpe** [comment]
It looks like this has been fixed upstream, as it now works correctly on my system. Can you confirm?

**Comment by decathorpe** [comment]
Closing this issue since I cannot confirm this anymore (and fedora 23 is EOL anyway).
